# Generated by Django 5.2.7 on 2026-01-17 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_arabic', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_arabic', models.CharField(blank=True, max_length=200)),
                ('title_original', models.CharField(blank=True, max_length=200)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('description', models.TextField()),
                ('description_arabic', models.TextField(blank=True)),
                ('country', models.CharField(choices=[('korean', 'Korean'), ('turkish', 'Turkish'), ('indian', 'Indian')], max_length=50)),
                ('total_episodes', models.IntegerField()),
                ('episode_duration', models.IntegerField()),
                ('release_year', models.IntegerField()),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=20)),
                ('next_episode_date', models.DateTimeField(blank=True, null=True)),
                ('current_episode_number', models.IntegerField(default=0)),
                ('genres', models.ManyToManyField(to='Tafarraj.genre')),
            ],
        ),
        migrations.CreateModel(
            name='WatchLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('language', models.CharField(choices=[('arabic', 'Arabic Subs'), ('english', 'English Subs')], max_length=20)),
                ('episodes_available', models.IntegerField()),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='Tafarraj.drama')),
            ],
        ),
    ]
