# Generated by Django 5.2.7 on 2026-01-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafarraj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='country',
            field=models.CharField(choices=[('korean', 'كوري'), ('turkish', 'تركي'), ('indian', 'هندي'), ('chinese', 'صيني')], max_length=50),
        ),
    ]
