# Generated by Django 5.2.7 on 2026-01-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafarraj', '0002_alter_drama_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='status',
            field=models.CharField(choices=[('ongoing', 'مستمر'), ('completed', 'مكتمل')], max_length=20),
        ),
    ]
