# Generated by Django 5.2.7 on 2026-02-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafarraj', '0004_drama_thumbnail_url_alter_drama_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='country',
            field=models.CharField(choices=[('korean', 'كوري'), ('turkish', 'تركي'), ('indian', 'هندي'), ('chinese', 'صيني'), ('moroccan', 'مغربي')], max_length=50),
        ),
    ]
