# Generated by Django 5.2.7 on 2026-02-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafarraj', '0005_alter_drama_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlink',
            name='last_scraped',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='watchlink',
            name='normalized_title',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='watchlink',
            name='scraped_from_site',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
