# Generated by Django 6.0.1 on 2026-02-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafarraj', '0006_watchlink_last_scraped_watchlink_normalized_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='country',
            field=models.CharField(choices=[('korean', 'كوري'), ('turkish', 'تركي'), ('Japanese', 'ياباني'), ('chinese', 'صيني'), ('moroccan', 'مغربي')], max_length=50),
        ),
    ]
