# Generated by Django 6.0.1 on 2026-02-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafarraj', '0007_alter_drama_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalStreamingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('countries', models.JSONField(default=list)),
                ('has_arabic_subs', models.BooleanField(default=True)),
                ('requires_subscription', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
