# Generated by Django 6.0.1 on 2026-02-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafarraj', '0008_externalstreamingsite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalStreamingSite',
        ),
        migrations.RemoveField(
            model_name='watchlink',
            name='last_scraped',
        ),
        migrations.RemoveField(
            model_name='watchlink',
            name='normalized_title',
        ),
        migrations.RemoveField(
            model_name='watchlink',
            name='scraped_from_site',
        ),
        migrations.AlterField(
            model_name='drama',
            name='country',
            field=models.CharField(choices=[('korean', 'كوري'), ('turkish', 'تركي'), ('japanese', 'ياباني'), ('chinese', 'صيني'), ('moroccan', 'مغربي')], max_length=50),
        ),
    ]
